//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBP_BazeEntities : DbContext
    {
        public TBP_BazeEntities()
            : base("name=TBP_BazeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac> Dobavljac { get; set; }
        public virtual DbSet<Narudzba> Narudzba { get; set; }
        public virtual DbSet<Narudzba_has_Roba> Narudzba_has_Roba { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
        public virtual DbSet<Proizvod_has_Roba> Proizvod_has_Roba { get; set; }
        public virtual DbSet<Radni_nalog> Radni_nalog { get; set; }
        public virtual DbSet<Radni_nalog_has_Proizvod> Radni_nalog_has_Proizvod { get; set; }
        public virtual DbSet<Roba> Roba { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
