//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzba()
        {
            this.Narudzba_has_Roba = new HashSet<Narudzba_has_Roba>();
        }
    
        public int idNarudzba { get; set; }
        public System.DateTime datum { get; set; }
        public string opis { get; set; }
        public int Zaposlenik_idZaposlenik { get; set; }
        public Nullable<int> zaprimljeno { get; set; }
        public int Dobavljac_idDobavljac { get; set; }
    
        public virtual Dobavljac Dobavljac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba_has_Roba> Narudzba_has_Roba { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
