//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radni_nalog_has_Proizvod
    {
        public int Radni_nalog_idRadni_nalog { get; set; }
        public int Proizvod_idProizvod { get; set; }
        public int kolicina { get; set; }
    
        public virtual Proizvod Proizvod { get; set; }
        public virtual Radni_nalog Radni_nalog { get; set; }
    }
}
