//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radni_nalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radni_nalog()
        {
            this.Radni_nalog_has_Proizvod = new HashSet<Radni_nalog_has_Proizvod>();
        }
    
        public int idRadni_nalog { get; set; }
        public System.DateTime datum { get; set; }
        public string opis { get; set; }
        public int Zaposlenik_idZaposlenik { get; set; }
        public int zavrseno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radni_nalog_has_Proizvod> Radni_nalog_has_Proizvod { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
