//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roba()
        {
            this.Narudzba_has_Roba = new HashSet<Narudzba_has_Roba>();
            this.Proizvod_has_Roba = new HashSet<Proizvod_has_Roba>();
        }
    
        public int idRoba { get; set; }
        public string naziv { get; set; }
        public decimal cijena_skladistenja { get; set; }
        public int trenutna_kolicina { get; set; }
        public int min_kolicina { get; set; }
        public decimal cijena_jedne_nabave { get; set; }
        public int trajanje_dostave { get; set; }
        public System.DateTime datum { get; set; }
        public int potraznja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba_has_Roba> Narudzba_has_Roba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvod_has_Roba> Proizvod_has_Roba { get; set; }
    }
}
